[package]
name    = "noirnet-vm"
version.workspace = true
edition.workspace = true

[dependencies]
noirnet-types   = { workspace = true }
noirnet-storage = { workspace = true }
noirnet-crypto  = { workspace = true }
wasmtime        = { workspace = true }
thiserror       = { workspace = true }
tracing         = { workspace = true }
blake3          = { workspace = true }
