[package]
name    = "noirnet-storage"
version.workspace = true
edition.workspace = true

[dependencies]
noirnet-types  = { workspace = true }
noirnet-crypto = { workspace = true }
sled           = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
bincode        = { workspace = true }
blake3         = { workspace = true }
thiserror      = { workspace = true }
tracing        = { workspace = true }
parking_lot    = { workspace = true }
num_cpus       = { workspace = true }

[dev-dependencies]
tempdir = "0.3.7"
tempfile       = { workspace = true }
